# -*- coding: utf-8 -*-
"""CICIDS dataset.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NbMFqXbYB_KFeg7oLLzmt4sHOtgYYq2M
"""

# =========================================================
# FINAL CHOIR-IDS (FULL RESEARCH PIPELINE)
# RF + CATBOOST + BiLSTM + ATTENTION
# + ROC + CM + SHAP + LIME + CALIBRATION
# =========================================================

!pip install lime shap -q

import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

import matplotlib
matplotlib.rcParams['figure.dpi'] = 100
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler, LabelEncoder, label_binarize
from sklearn.metrics import *
from sklearn.calibration import CalibratedClassifierCV, calibration_curve

from sklearn.ensemble import RandomForestClassifier
from catboost import CatBoostClassifier

import shap
from lime.lime_tabular import LimeTabularExplainer

import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import *
from tensorflow.keras.callbacks import EarlyStopping

# =========================
# LOAD CSV SAFELY
# =========================
def load_csv(path):
    df = pd.read_csv(path, engine='python', on_bad_lines='skip')
    df.columns = df.columns.str.strip()
    return df

# =========================
# LOAD DATA
# =========================
df1 = load_csv("/content/Monday-WorkingHours.pcap_ISCX.csv")
df2 = load_csv("/content/Tuesday-WorkingHours.pcap_ISCX.csv")
df3 = load_csv("/content/Wednesday-workingHours.pcap_ISCX.csv")
df4 = load_csv("/content/Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv")
df5 = load_csv("/content/Friday-WorkingHours-Morning.pcap_ISCX.csv")

# =========================
# LABEL MAPPING (APPLIED BEFORE REDUCE)
# =========================
label_col = [c for c in df1.columns if 'label' in c.lower()][0]

def map_label(x):
    x = str(x).strip().upper()
    if 'BENIGN' in x:                    return 'Normal'
    elif 'DOS' in x or 'DDOS' in x:     return 'DoS'
    elif 'PORT' in x or 'SCAN' in x:    return 'Probe'
    elif 'BOT' in x:                     return 'Probe'
    elif 'BRUTE' in x or 'PATATOR' in x: return 'BruteForce'
    elif 'WEB' in x or 'SQL' in x:      return 'WebAttack'
    else:                                return 'Other'

for df in [df1, df2, df3, df4, df5]:
    df[label_col] = df[label_col].apply(map_label)

print("Label distributions before reduce:")
for i, df in enumerate([df1, df2, df3, df4, df5], 1):
    print(f"  df{i}: {df[label_col].value_counts().to_dict()}")

# =========================
# REDUCE SIZE — BUT KEEP ALL CLASSES
# =========================
def reduce_balanced(df, n_per_class=5000):
    """Sample up to n_per_class rows per class to keep all classes."""
    return df.groupby(label_col, group_keys=False).apply(
        lambda x: x.sample(n=min(n_per_class, len(x)), random_state=42)
    ).reset_index(drop=True)

df1 = reduce_balanced(df1)
df2 = reduce_balanced(df2)
df3 = reduce_balanced(df3)
df4 = reduce_balanced(df4)
df5 = reduce_balanced(df5)

train_df = pd.concat([df1, df2, df3, df4], ignore_index=True)
test_df  = df5.copy()

print("\nAfter reduce:")
print("Train label dist:\n", train_df[label_col].value_counts())
print("Test  label dist:\n", test_df[label_col].value_counts())

# =========================
# CLEAN
# =========================
def clean(df):
    df.replace([np.inf, -np.inf], np.nan, inplace=True)
    df.dropna(inplace=True)
    return df

train_df = clean(train_df)
test_df  = clean(test_df)

# =========================
# COMMON CLASSES — ENSURE MINIMUM 2 CLASSES
# =========================
common = sorted(list(set(train_df[label_col]) & set(test_df[label_col])))
print("\nCommon classes:", common)

# Safety check
if len(common) < 2:
    # If test has too few classes, use ALL train classes and fill test gaps
    print("⚠️  Test set has too few classes — using full train label set")
    common = sorted(train_df[label_col].unique().tolist())
    # Add missing classes to test from train
    missing = [c for c in common if c not in test_df[label_col].values]
    for c in missing:
        extra = train_df[train_df[label_col] == c].sample(
            n=min(100, len(train_df[train_df[label_col] == c])), random_state=42
        )
        test_df = pd.concat([test_df, extra], ignore_index=True)
    print("Classes after fix:", common)

train_df = train_df[train_df[label_col].isin(common)]
test_df  = test_df[test_df[label_col].isin(common)]

print(f"\nFinal Train: {train_df.shape}  |  Test: {test_df.shape}")
print("Train classes:", train_df[label_col].value_counts().to_dict())
print("Test  classes:", test_df[label_col].value_counts().to_dict())

# =========================
# FEATURES & TARGET
# =========================
X_train = train_df.drop(columns=[label_col]).apply(pd.to_numeric, errors='coerce').fillna(0)
X_test  = test_df.drop(columns=[label_col]).apply(pd.to_numeric, errors='coerce').fillna(0)

y_train_raw = train_df[label_col]
y_test_raw  = test_df[label_col]

le = LabelEncoder()
le.fit(common)

y_train = le.transform(y_train_raw)
y_test  = le.transform(y_test_raw)

print("\nEncoded classes:", list(zip(range(len(le.classes_)), le.classes_)))

# =========================
# SCALE
# =========================
scaler  = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test  = scaler.transform(X_test)

# =========================
# BASE MODELS
# =========================
print("\n🏋️ Training Random Forest...")
rf = RandomForestClassifier(n_estimators=50, n_jobs=-1, random_state=42)
rf.fit(X_train, y_train)

print("🏋️ Training CatBoost...")
cat = CatBoostClassifier(
    iterations=200,
    depth=6,
    learning_rate=0.1,
    verbose=0,
    random_state=42
)
cat.fit(X_train, y_train)

# =========================
# CALIBRATION
# =========================
print("🏋️ Training Calibrated models...")
rf_sig = CalibratedClassifierCV(rf, method='sigmoid',  cv='prefit')
rf_iso = CalibratedClassifierCV(rf, method='isotonic', cv='prefit')

rf_sig.fit(X_train, y_train)
rf_iso.fit(X_train, y_train)

# =========================
# META FEATURES FOR BiLSTM
# =========================
meta_train = np.hstack((rf.predict_proba(X_train), cat.predict_proba(X_train)))
meta_test  = np.hstack((rf.predict_proba(X_test),  cat.predict_proba(X_test)))

meta_train = meta_train.reshape((meta_train.shape[0], 1, meta_train.shape[1]))
meta_test  = meta_test.reshape((meta_test.shape[0],   1, meta_test.shape[1]))

n_classes   = len(common)
y_train_cat = tf.keras.utils.to_categorical(y_train, num_classes=n_classes)

# =========================
# ATTENTION LAYER
# =========================
def attention(x):
    w = Dense(x.shape[-1], activation='tanh')(x)
    w = Softmax(axis=1)(w)
    x = Multiply()([x, w])
    return Lambda(lambda t: tf.reduce_sum(t, axis=1))(x)

# =========================
# BiLSTM + ATTENTION MODEL
# =========================
print("🏋️ Training BiLSTM + Attention model...")
inp = Input(shape=(1, meta_train.shape[2]))
x   = Bidirectional(LSTM(32, return_sequences=True))(inp)
x   = attention(x)
out = Dense(n_classes, activation='softmax')(x)

model = Model(inp, out)
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

early = EarlyStopping(patience=3, restore_best_weights=True)

model.fit(meta_train, y_train_cat,
          epochs=10,
          batch_size=512,
          validation_split=0.2,
          callbacks=[early],
          verbose=1)

# =========================
# PREDICTION
# =========================
y_prob = model.predict(meta_test)
y_pred = np.argmax(y_prob, axis=1)

# =========================
# METRICS
# =========================
print("\n========== CHOIR-IDS RESULTS (CICIDS2017) ==========")
print(f"Accuracy  : {accuracy_score(y_test, y_pred):.4f}")
print(f"Precision : {precision_score(y_test, y_pred, average='weighted', zero_division=0):.4f}")
print(f"Recall    : {recall_score(y_test, y_pred, average='weighted', zero_division=0):.4f}")
print(f"F1 Score  : {f1_score(y_test, y_pred, average='weighted', zero_division=0):.4f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=le.classes_, zero_division=0))

# =========================
# PLOT 1 — CONFUSION MATRIX
# =========================
plt.figure(figsize=(9, 7))
cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=le.classes_, yticklabels=le.classes_)
plt.xlabel("Predicted Label", fontsize=12)
plt.ylabel("True Label", fontsize=12)
plt.title("Confusion Matrix — CHOIR-IDS (CICIDS2017)", fontsize=14, fontweight='bold')
plt.tight_layout(pad=3.0)
plt.savefig("confusion_matrix.png", dpi=300, bbox_inches='tight')
plt.show()
plt.close()
print("✅ Confusion Matrix saved.\n")

# =========================
# PLOT 2 — ROC-AUC CURVE
# =========================
plt.figure(figsize=(9, 7))

y_test_bin = label_binarize(y_test, classes=list(range(n_classes)))
colors     = ['blue', 'red', 'green', 'orange', 'purple', 'brown', 'cyan']

plotted = 0
for i in range(n_classes):
    if i >= y_prob.shape[1]:
        continue
    if np.sum(y_test_bin[:, i]) == 0:
        print(f"⚠️  Skipping '{le.classes_[i]}' — not in test set")
        continue
    fpr, tpr, _ = roc_curve(y_test_bin[:, i], y_prob[:, i])
    auc_score   = auc(fpr, tpr)
    plt.plot(fpr, tpr, color=colors[i % len(colors)], linewidth=2,
             label=f"{le.classes_[i]} (AUC = {auc_score:.2f})")
    plotted += 1

plt.plot([0, 1], [0, 1], 'k--', linewidth=1.5, label='Random Classifier')
plt.xlabel("False Positive Rate", fontsize=13)
plt.ylabel("True Positive Rate", fontsize=13)
plt.title("ROC-AUC Curve — CHOIR-IDS (CICIDS2017)", fontsize=14, fontweight='bold')
plt.legend(loc='lower right', fontsize=10)
plt.grid(alpha=0.3)
plt.tight_layout(pad=3.0)
plt.savefig("roc_auc_curve.png", dpi=300, bbox_inches='tight')
plt.show()
plt.close()
print("✅ ROC-AUC Curve saved.\n")

# =========================
# PLOT 3 — CALIBRATION CURVE
# =========================
plt.figure(figsize=(7, 6))

y_binary = (y_test == 0).astype(int)

prob_sig = rf_sig.predict_proba(X_test)[:, 0]
prob_iso = rf_iso.predict_proba(X_test)[:, 0]

frac_sig, mean_sig = calibration_curve(y_binary, prob_sig, n_bins=10)
frac_iso, mean_iso = calibration_curve(y_binary, prob_iso, n_bins=10)

plt.plot(mean_sig, frac_sig, marker='o', color='blue',   linewidth=2, label='Sigmoid Calibration')
plt.plot(mean_iso, frac_iso, marker='s', color='orange', linewidth=2, label='Isotonic Calibration')
plt.plot([0, 1], [0, 1], 'k--', label='Perfect Calibration')
plt.xlabel("Mean Predicted Probability", fontsize=12)
plt.ylabel("Fraction of Positives", fontsize=12)
plt.title("Calibration Curve — CHOIR-IDS", fontsize=14, fontweight='bold')
plt.legend(fontsize=11)
plt.grid(alpha=0.3)
plt.tight_layout(pad=3.0)
plt.savefig("calibration_curve.png", dpi=300, bbox_inches='tight')
plt.show()
plt.close()
print("✅ Calibration Curve saved.\n")

# =========================
# PLOT 4 — SHAP SUMMARY (BAR)
# =========================
print("⏳ Computing SHAP values...")

feature_names = [f"Feature {i}" for i in range(X_train.shape[1])]
shap_explainer = shap.TreeExplainer(rf)
shap_sample    = X_test[:300]
shap_vals      = shap_explainer.shap_values(shap_sample)

# For multiclass, shap_vals is a list — take mean absolute across all classes
if isinstance(shap_vals, list):
    shap_vals_mean = np.mean([np.abs(sv) for sv in shap_vals], axis=0)
else:
    shap_vals_mean = np.abs(shap_vals)

plt.figure(figsize=(10, 7))
shap.summary_plot(
    shap_vals_mean,
    shap_sample,
    feature_names=feature_names,
    plot_type="bar",
    max_display=15,
    show=False
)
plt.title("SHAP Feature Importance — CHOIR-IDS", fontsize=14, fontweight='bold')
plt.tight_layout(pad=3.0)
plt.savefig("shap_summary.png", dpi=300, bbox_inches='tight')
plt.show()
plt.close()
print("✅ SHAP Summary saved.\n")

# =========================
# PLOT 5 — LIME EXPLANATION
# =========================
print("⏳ Computing LIME explanation...")

lime_exp = LimeTabularExplainer(
    X_train,
    feature_names=feature_names,
    class_names=le.classes_,
    mode='classification'
)

exp = lime_exp.explain_instance(X_test[0], rf.predict_proba, num_features=15)

fig = exp.as_pyplot_figure()
fig.set_size_inches(10, 7)
plt.title("LIME Explanation — Sample Instance", fontsize=14, fontweight='bold')
plt.tight_layout(pad=3.0)
plt.savefig("lime_explanation.png", dpi=300, bbox_inches='tight')
plt.show()
plt.close()
print("✅ LIME Explanation saved.\n")

print("\n🎉 ALL DONE! Files saved:")
print("   → confusion_matrix.png")
print("   → roc_auc_curve.png")
print("   → calibration_curve.png")
print("   → shap_summary.png")
print("   → lime_explanation.png")